/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'answers' : IDL.Vec(IDL.Text),
  'correctAnswerIndex' : IDL.Nat,
});
export const Quiz = IDL.Record({
  'id' : IDL.Text,
  'questions' : IDL.Vec(QuizQuestion),
  'videoId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'status' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Time = IDL.Int;
export const QuizResult = IDL.Record({
  'user' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : Time,
  'quizId' : IDL.Text,
});
export const Theme = IDL.Record({
  'primaryColor' : IDL.Text,
  'secondaryColor' : IDL.Text,
});
export const DashboardVisuals = IDL.Record({
  'headingColor' : IDL.Text,
  'gradientDefinition' : IDL.Text,
  'backgroundColorOverlay' : IDL.Text,
  'accentColor' : IDL.Text,
  'cardAccentColor' : IDL.Text,
  'headerBackgroundColor' : IDL.Text,
  'cardBackgroundColor' : IDL.Text,
  'graphCardBackground' : IDL.Text,
  'overlayOpacity' : IDL.Nat,
  'secondaryHeadingColor' : IDL.Text,
  'gradientTransform' : IDL.Text,
  'cardTextColor' : IDL.Text,
});
export const HomepageVisuals = IDL.Record({
  'subtitleColor' : IDL.Text,
  'headingColor' : IDL.Text,
  'supportingTextColor' : IDL.Text,
  'backgroundColorOverlay' : IDL.Text,
  'heroBackgroundColor' : IDL.Text,
  'buttonTextColor' : IDL.Text,
  'cardBackgroundColor' : IDL.Text,
  'heroImage' : IDL.Opt(ExternalBlob),
  'buttonColor' : IDL.Text,
  'bannerBackgroundColor' : IDL.Text,
  'overlayOpacity' : IDL.Nat,
  'headingShadowColor' : IDL.Text,
  'cardTextColor' : IDL.Text,
});
export const AdminConfig = IDL.Record({
  'donationLink' : IDL.Text,
  'homePageSubText' : IDL.Text,
  'theme' : Theme,
  'homePageSupportingText' : IDL.Text,
  'logo' : IDL.Opt(ExternalBlob),
  'errorMessage' : IDL.Text,
  'pageNotFoundTitle' : IDL.Text,
  'emptyStateTitle' : IDL.Text,
  'errorTitle' : IDL.Text,
  'homeHeroHeading' : IDL.Text,
  'dashboardVisuals' : DashboardVisuals,
  'homepageVisuals' : HomepageVisuals,
  'homePageText' : IDL.Text,
  'homeHeroSupportingText' : IDL.Text,
  'emptyStateMessage' : IDL.Text,
  'pageNotFoundMessage' : IDL.Text,
});
export const Settings = IDL.Record({
  'donationLink' : IDL.Text,
  'theme' : Theme,
  'siteName' : IDL.Text,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'category' : IDL.Text,
});
export const SettingsData = IDL.Record({
  'categories' : IDL.Vec(Category),
  'adminConfig' : AdminConfig,
  'settings' : Settings,
  'videos' : IDL.Vec(Video),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([Category], [], []),
  'addVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createQuiz' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(QuizQuestion)], [], []),
  'deleteCategory' : IDL.Func([Category], [], []),
  'deleteQuiz' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAllQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getMyQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getQuiz' : IDL.Func([IDL.Text], [IDL.Opt(Quiz)], ['query']),
  'getQuizzesByVideo' : IDL.Func([IDL.Text], [IDL.Vec(Quiz)], ['query']),
  'getSettingsData' : IDL.Func([], [SettingsData], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'takeQuiz' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'updateAdminConfig' : IDL.Func([AdminConfig], [], []),
  'updateDashboardVisuals' : IDL.Func([DashboardVisuals], [], []),
  'updateDonationLink' : IDL.Func([IDL.Text], [], []),
  'updateHomePageText' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateHomepageVisuals' : IDL.Func([HomepageVisuals], [], []),
  'updateLogo' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  'updateQuiz' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(QuizQuestion)], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
  'updateTheme' : IDL.Func([Theme], [], []),
  'updateUserStatus' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'answers' : IDL.Vec(IDL.Text),
    'correctAnswerIndex' : IDL.Nat,
  });
  const Quiz = IDL.Record({
    'id' : IDL.Text,
    'questions' : IDL.Vec(QuizQuestion),
    'videoId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'status' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const Time = IDL.Int;
  const QuizResult = IDL.Record({
    'user' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : Time,
    'quizId' : IDL.Text,
  });
  const Theme = IDL.Record({
    'primaryColor' : IDL.Text,
    'secondaryColor' : IDL.Text,
  });
  const DashboardVisuals = IDL.Record({
    'headingColor' : IDL.Text,
    'gradientDefinition' : IDL.Text,
    'backgroundColorOverlay' : IDL.Text,
    'accentColor' : IDL.Text,
    'cardAccentColor' : IDL.Text,
    'headerBackgroundColor' : IDL.Text,
    'cardBackgroundColor' : IDL.Text,
    'graphCardBackground' : IDL.Text,
    'overlayOpacity' : IDL.Nat,
    'secondaryHeadingColor' : IDL.Text,
    'gradientTransform' : IDL.Text,
    'cardTextColor' : IDL.Text,
  });
  const HomepageVisuals = IDL.Record({
    'subtitleColor' : IDL.Text,
    'headingColor' : IDL.Text,
    'supportingTextColor' : IDL.Text,
    'backgroundColorOverlay' : IDL.Text,
    'heroBackgroundColor' : IDL.Text,
    'buttonTextColor' : IDL.Text,
    'cardBackgroundColor' : IDL.Text,
    'heroImage' : IDL.Opt(ExternalBlob),
    'buttonColor' : IDL.Text,
    'bannerBackgroundColor' : IDL.Text,
    'overlayOpacity' : IDL.Nat,
    'headingShadowColor' : IDL.Text,
    'cardTextColor' : IDL.Text,
  });
  const AdminConfig = IDL.Record({
    'donationLink' : IDL.Text,
    'homePageSubText' : IDL.Text,
    'theme' : Theme,
    'homePageSupportingText' : IDL.Text,
    'logo' : IDL.Opt(ExternalBlob),
    'errorMessage' : IDL.Text,
    'pageNotFoundTitle' : IDL.Text,
    'emptyStateTitle' : IDL.Text,
    'errorTitle' : IDL.Text,
    'homeHeroHeading' : IDL.Text,
    'dashboardVisuals' : DashboardVisuals,
    'homepageVisuals' : HomepageVisuals,
    'homePageText' : IDL.Text,
    'homeHeroSupportingText' : IDL.Text,
    'emptyStateMessage' : IDL.Text,
    'pageNotFoundMessage' : IDL.Text,
  });
  const Settings = IDL.Record({
    'donationLink' : IDL.Text,
    'theme' : Theme,
    'siteName' : IDL.Text,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'category' : IDL.Text,
  });
  const SettingsData = IDL.Record({
    'categories' : IDL.Vec(Category),
    'adminConfig' : AdminConfig,
    'settings' : Settings,
    'videos' : IDL.Vec(Video),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([Category], [], []),
    'addVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createQuiz' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(QuizQuestion)],
        [],
        [],
      ),
    'deleteCategory' : IDL.Func([Category], [], []),
    'deleteQuiz' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAllQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getMyQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getQuiz' : IDL.Func([IDL.Text], [IDL.Opt(Quiz)], ['query']),
    'getQuizzesByVideo' : IDL.Func([IDL.Text], [IDL.Vec(Quiz)], ['query']),
    'getSettingsData' : IDL.Func([], [SettingsData], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'takeQuiz' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'updateAdminConfig' : IDL.Func([AdminConfig], [], []),
    'updateDashboardVisuals' : IDL.Func([DashboardVisuals], [], []),
    'updateDonationLink' : IDL.Func([IDL.Text], [], []),
    'updateHomePageText' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateHomepageVisuals' : IDL.Func([HomepageVisuals], [], []),
    'updateLogo' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
    'updateQuiz' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(QuizQuestion)],
        [],
        [],
      ),
    'updateSettings' : IDL.Func([Settings], [], []),
    'updateTheme' : IDL.Func([Theme], [], []),
    'updateUserStatus' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };