/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminConfig {
  'donationLink' : string,
  'homePageSubText' : string,
  'theme' : Theme,
  'homePageSupportingText' : string,
  'logo' : [] | [ExternalBlob],
  'errorMessage' : string,
  'pageNotFoundTitle' : string,
  'emptyStateTitle' : string,
  'errorTitle' : string,
  'homeHeroHeading' : string,
  'dashboardVisuals' : DashboardVisuals,
  'homepageVisuals' : HomepageVisuals,
  'homePageText' : string,
  'homeHeroSupportingText' : string,
  'emptyStateMessage' : string,
  'pageNotFoundMessage' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Category = string;
export interface DashboardVisuals {
  'headingColor' : string,
  'gradientDefinition' : string,
  'backgroundColorOverlay' : string,
  'accentColor' : string,
  'cardAccentColor' : string,
  'headerBackgroundColor' : string,
  'cardBackgroundColor' : string,
  'graphCardBackground' : string,
  'overlayOpacity' : bigint,
  'secondaryHeadingColor' : string,
  'gradientTransform' : string,
  'cardTextColor' : string,
}
export type ExternalBlob = Uint8Array;
export interface HomepageVisuals {
  'subtitleColor' : string,
  'headingColor' : string,
  'supportingTextColor' : string,
  'backgroundColorOverlay' : string,
  'heroBackgroundColor' : string,
  'buttonTextColor' : string,
  'cardBackgroundColor' : string,
  'heroImage' : [] | [ExternalBlob],
  'buttonColor' : string,
  'bannerBackgroundColor' : string,
  'overlayOpacity' : bigint,
  'headingShadowColor' : string,
  'cardTextColor' : string,
}
export interface Quiz {
  'id' : string,
  'questions' : Array<QuizQuestion>,
  'videoId' : string,
}
export interface QuizQuestion {
  'question' : string,
  'answers' : Array<string>,
  'correctAnswerIndex' : bigint,
}
export interface QuizResult {
  'user' : string,
  'score' : bigint,
  'timestamp' : Time,
  'quizId' : string,
}
export interface Settings {
  'donationLink' : string,
  'theme' : Theme,
  'siteName' : string,
}
export interface SettingsData {
  'categories' : Array<Category>,
  'adminConfig' : AdminConfig,
  'settings' : Settings,
  'videos' : Array<Video>,
}
export interface Theme { 'primaryColor' : string, 'secondaryColor' : string }
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'status' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'url' : string,
  'title' : string,
  'thumbnail' : ExternalBlob,
  'category' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[Category], undefined>,
  'addVideo' : ActorMethod<
    [string, string, string, string, ExternalBlob],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createQuiz' : ActorMethod<[string, string, Array<QuizQuestion>], undefined>,
  'deleteCategory' : ActorMethod<[Category], undefined>,
  'deleteQuiz' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAllQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getLeaderboard' : ActorMethod<[], Array<QuizResult>>,
  'getMyQuizResults' : ActorMethod<[], Array<QuizResult>>,
  'getQuiz' : ActorMethod<[string], [] | [Quiz]>,
  'getQuizzesByVideo' : ActorMethod<[string], Array<Quiz>>,
  'getSettingsData' : ActorMethod<[], SettingsData>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideos' : ActorMethod<[], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'takeQuiz' : ActorMethod<[string, Array<bigint>], bigint>,
  'updateAdminConfig' : ActorMethod<[AdminConfig], undefined>,
  'updateDashboardVisuals' : ActorMethod<[DashboardVisuals], undefined>,
  'updateDonationLink' : ActorMethod<[string], undefined>,
  'updateHomePageText' : ActorMethod<[string, string, string], undefined>,
  'updateHomepageVisuals' : ActorMethod<[HomepageVisuals], undefined>,
  'updateLogo' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'updateQuiz' : ActorMethod<[string, string, Array<QuizQuestion>], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
  'updateTheme' : ActorMethod<[Theme], undefined>,
  'updateUserStatus' : ActorMethod<[Principal, string], undefined>,
  'updateVideo' : ActorMethod<
    [string, string, string, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];