/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: string;
    url: string;
    title: string;
    thumbnail: ExternalBlob;
    category: string;
}
export type Category = string;
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface QuizQuestion {
    question: string;
    answers: Array<string>;
    correctAnswerIndex: bigint;
}
export interface Quiz {
    id: string;
    questions: Array<QuizQuestion>;
    videoId: string;
}
export interface SettingsData {
    categories: Array<Category>;
    adminConfig: AdminConfig;
    settings: Settings;
    videos: Array<Video>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface QuizResult {
    user: string;
    score: bigint;
    timestamp: Time;
    quizId: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Settings {
    donationLink: string;
    theme: Theme;
    siteName: string;
}
export interface HomepageVisuals {
    subtitleColor: string;
    headingColor: string;
    supportingTextColor: string;
    backgroundColorOverlay: string;
    heroBackgroundColor: string;
    buttonTextColor: string;
    cardBackgroundColor: string;
    heroImage?: ExternalBlob;
    buttonColor: string;
    bannerBackgroundColor: string;
    overlayOpacity: bigint;
    headingShadowColor: string;
    cardTextColor: string;
}
export interface AdminConfig {
    donationLink: string;
    homePageSubText: string;
    theme: Theme;
    homePageSupportingText: string;
    logo?: ExternalBlob;
    errorMessage: string;
    pageNotFoundTitle: string;
    emptyStateTitle: string;
    errorTitle: string;
    homeHeroHeading: string;
    dashboardVisuals: DashboardVisuals;
    homepageVisuals: HomepageVisuals;
    homePageText: string;
    homeHeroSupportingText: string;
    emptyStateMessage: string;
    pageNotFoundMessage: string;
}
export interface Theme {
    primaryColor: string;
    secondaryColor: string;
}
export interface DashboardVisuals {
    headingColor: string;
    gradientDefinition: string;
    backgroundColorOverlay: string;
    accentColor: string;
    cardAccentColor: string;
    headerBackgroundColor: string;
    cardBackgroundColor: string;
    graphCardBackground: string;
    overlayOpacity: bigint;
    secondaryHeadingColor: string;
    gradientTransform: string;
    cardTextColor: string;
}
export interface UserProfile {
    status: string;
    name: string;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCategory(category: Category): Promise<void>;
    addVideo(id: string, title: string, category: string, url: string, thumbnail: ExternalBlob): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createQuiz(id: string, videoId: string, questions: Array<QuizQuestion>): Promise<void>;
    deleteCategory(category: Category): Promise<void>;
    deleteQuiz(id: string): Promise<void>;
    deleteVideo(id: string): Promise<void>;
    getAllQuizzes(): Promise<Array<Quiz>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategories(): Promise<Array<Category>>;
    getLeaderboard(): Promise<Array<QuizResult>>;
    getMyQuizResults(): Promise<Array<QuizResult>>;
    getQuiz(id: string): Promise<Quiz | null>;
    getQuizzesByVideo(videoId: string): Promise<Array<Quiz>>;
    getSettingsData(): Promise<SettingsData>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideos(): Promise<Array<Video>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    takeQuiz(quizId: string, answers: Array<bigint>): Promise<bigint>;
    updateAdminConfig(config: AdminConfig): Promise<void>;
    updateDashboardVisuals(visuals: DashboardVisuals): Promise<void>;
    updateDonationLink(link: string): Promise<void>;
    updateHomePageText(text: string, subText: string, supportingText: string): Promise<void>;
    updateHomepageVisuals(visuals: HomepageVisuals): Promise<void>;
    updateLogo(logo: ExternalBlob | null): Promise<void>;
    updateQuiz(id: string, videoId: string, questions: Array<QuizQuestion>): Promise<void>;
    updateSettings(newSettings: Settings): Promise<void>;
    updateTheme(theme: Theme): Promise<void>;
    updateUserStatus(user: Principal, status: string): Promise<void>;
    updateVideo(id: string, title: string, category: string, url: string, thumbnail: ExternalBlob): Promise<void>;
}
import type { AdminConfig as _AdminConfig, ApprovalStatus as _ApprovalStatus, Category as _Category, DashboardVisuals as _DashboardVisuals, ExternalBlob as _ExternalBlob, HomepageVisuals as _HomepageVisuals, Quiz as _Quiz, Settings as _Settings, SettingsData as _SettingsData, Theme as _Theme, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCategory(arg0: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0);
            return result;
        }
    }
    async addVideo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideo(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideo(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createQuiz(arg0: string, arg1: string, arg2: Array<QuizQuestion>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCategory(arg0: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteQuiz(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuiz(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async getAllQuizzes(): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuizzes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuizzes();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMyQuizResults(): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuizResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuizResults();
            return result;
        }
    }
    async getQuiz(arg0: string): Promise<Quiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizzesByVideo(arg0: string): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizzesByVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizzesByVideo(arg0);
            return result;
        }
    }
    async getSettingsData(): Promise<SettingsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettingsData();
                return from_candid_SettingsData_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettingsData();
            return from_candid_SettingsData_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideos();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideos();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async takeQuiz(arg0: string, arg1: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.takeQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.takeQuiz(arg0, arg1);
            return result;
        }
    }
    async updateAdminConfig(arg0: AdminConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminConfig(await to_candid_AdminConfig_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminConfig(await to_candid_AdminConfig_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDashboardVisuals(arg0: DashboardVisuals): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDashboardVisuals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDashboardVisuals(arg0);
            return result;
        }
    }
    async updateDonationLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonationLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonationLink(arg0);
            return result;
        }
    }
    async updateHomePageText(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomePageText(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomePageText(arg0, arg1, arg2);
            return result;
        }
    }
    async updateHomepageVisuals(arg0: HomepageVisuals): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomepageVisuals(await to_candid_HomepageVisuals_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomepageVisuals(await to_candid_HomepageVisuals_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLogo(arg0: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLogo(await to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLogo(await to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateQuiz(arg0: string, arg1: string, arg2: Array<QuizQuestion>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuiz(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuiz(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
    async updateTheme(arg0: Theme): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTheme(arg0);
            return result;
        }
    }
    async updateUserStatus(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserStatus(arg0, arg1);
            return result;
        }
    }
    async updateVideo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideo(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideo(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
async function from_candid_AdminConfig_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminConfig): Promise<AdminConfig> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_HomepageVisuals_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomepageVisuals): Promise<HomepageVisuals> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_SettingsData_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SettingsData): Promise<SettingsData> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quiz]): Quiz | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categories: Array<_Category>;
    adminConfig: _AdminConfig;
    settings: _Settings;
    videos: Array<_Video>;
}): Promise<{
    categories: Array<Category>;
    adminConfig: AdminConfig;
    settings: Settings;
    videos: Array<Video>;
}> {
    return {
        categories: value.categories,
        adminConfig: await from_candid_AdminConfig_n17(_uploadFile, _downloadFile, value.adminConfig),
        settings: value.settings,
        videos: await from_candid_vec_n23(_uploadFile, _downloadFile, value.videos)
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    donationLink: string;
    homePageSubText: string;
    theme: _Theme;
    homePageSupportingText: string;
    logo: [] | [_ExternalBlob];
    errorMessage: string;
    pageNotFoundTitle: string;
    emptyStateTitle: string;
    errorTitle: string;
    homeHeroHeading: string;
    dashboardVisuals: _DashboardVisuals;
    homepageVisuals: _HomepageVisuals;
    homePageText: string;
    homeHeroSupportingText: string;
    emptyStateMessage: string;
    pageNotFoundMessage: string;
}): Promise<{
    donationLink: string;
    homePageSubText: string;
    theme: Theme;
    homePageSupportingText: string;
    logo?: ExternalBlob;
    errorMessage: string;
    pageNotFoundTitle: string;
    emptyStateTitle: string;
    errorTitle: string;
    homeHeroHeading: string;
    dashboardVisuals: DashboardVisuals;
    homepageVisuals: HomepageVisuals;
    homePageText: string;
    homeHeroSupportingText: string;
    emptyStateMessage: string;
    pageNotFoundMessage: string;
}> {
    return {
        donationLink: value.donationLink,
        homePageSubText: value.homePageSubText,
        theme: value.theme,
        homePageSupportingText: value.homePageSupportingText,
        logo: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.logo)),
        errorMessage: value.errorMessage,
        pageNotFoundTitle: value.pageNotFoundTitle,
        emptyStateTitle: value.emptyStateTitle,
        errorTitle: value.errorTitle,
        homeHeroHeading: value.homeHeroHeading,
        dashboardVisuals: value.dashboardVisuals,
        homepageVisuals: await from_candid_HomepageVisuals_n21(_uploadFile, _downloadFile, value.homepageVisuals),
        homePageText: value.homePageText,
        homeHeroSupportingText: value.homeHeroSupportingText,
        emptyStateMessage: value.emptyStateMessage,
        pageNotFoundMessage: value.pageNotFoundMessage
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subtitleColor: string;
    headingColor: string;
    supportingTextColor: string;
    backgroundColorOverlay: string;
    heroBackgroundColor: string;
    buttonTextColor: string;
    cardBackgroundColor: string;
    heroImage: [] | [_ExternalBlob];
    buttonColor: string;
    bannerBackgroundColor: string;
    overlayOpacity: bigint;
    headingShadowColor: string;
    cardTextColor: string;
}): Promise<{
    subtitleColor: string;
    headingColor: string;
    supportingTextColor: string;
    backgroundColorOverlay: string;
    heroBackgroundColor: string;
    buttonTextColor: string;
    cardBackgroundColor: string;
    heroImage?: ExternalBlob;
    buttonColor: string;
    bannerBackgroundColor: string;
    overlayOpacity: bigint;
    headingShadowColor: string;
    cardTextColor: string;
}> {
    return {
        subtitleColor: value.subtitleColor,
        headingColor: value.headingColor,
        supportingTextColor: value.supportingTextColor,
        backgroundColorOverlay: value.backgroundColorOverlay,
        heroBackgroundColor: value.heroBackgroundColor,
        buttonTextColor: value.buttonTextColor,
        cardBackgroundColor: value.cardBackgroundColor,
        heroImage: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.heroImage)),
        buttonColor: value.buttonColor,
        bannerBackgroundColor: value.bannerBackgroundColor,
        overlayOpacity: value.overlayOpacity,
        headingShadowColor: value.headingShadowColor,
        cardTextColor: value.cardTextColor
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    title: string;
    thumbnail: _ExternalBlob;
    category: string;
}): Promise<{
    id: string;
    url: string;
    title: string;
    thumbnail: ExternalBlob;
    category: string;
}> {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        thumbnail: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.thumbnail),
        category: value.category
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n29(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n27(_uploadFile, _downloadFile, x));
}
async function to_candid_AdminConfig_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminConfig): Promise<_AdminConfig> {
    return await to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_HomepageVisuals_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomepageVisuals): Promise<_HomepageVisuals> {
    return await to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    donationLink: string;
    homePageSubText: string;
    theme: Theme;
    homePageSupportingText: string;
    logo?: ExternalBlob;
    errorMessage: string;
    pageNotFoundTitle: string;
    emptyStateTitle: string;
    errorTitle: string;
    homeHeroHeading: string;
    dashboardVisuals: DashboardVisuals;
    homepageVisuals: HomepageVisuals;
    homePageText: string;
    homeHeroSupportingText: string;
    emptyStateMessage: string;
    pageNotFoundMessage: string;
}): Promise<{
    donationLink: string;
    homePageSubText: string;
    theme: _Theme;
    homePageSupportingText: string;
    logo: [] | [_ExternalBlob];
    errorMessage: string;
    pageNotFoundTitle: string;
    emptyStateTitle: string;
    errorTitle: string;
    homeHeroHeading: string;
    dashboardVisuals: _DashboardVisuals;
    homepageVisuals: _HomepageVisuals;
    homePageText: string;
    homeHeroSupportingText: string;
    emptyStateMessage: string;
    pageNotFoundMessage: string;
}> {
    return {
        donationLink: value.donationLink,
        homePageSubText: value.homePageSubText,
        theme: value.theme,
        homePageSupportingText: value.homePageSupportingText,
        logo: value.logo ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.logo)) : candid_none(),
        errorMessage: value.errorMessage,
        pageNotFoundTitle: value.pageNotFoundTitle,
        emptyStateTitle: value.emptyStateTitle,
        errorTitle: value.errorTitle,
        homeHeroHeading: value.homeHeroHeading,
        dashboardVisuals: value.dashboardVisuals,
        homepageVisuals: await to_candid_HomepageVisuals_n35(_uploadFile, _downloadFile, value.homepageVisuals),
        homePageText: value.homePageText,
        homeHeroSupportingText: value.homeHeroSupportingText,
        emptyStateMessage: value.emptyStateMessage,
        pageNotFoundMessage: value.pageNotFoundMessage
    };
}
async function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subtitleColor: string;
    headingColor: string;
    supportingTextColor: string;
    backgroundColorOverlay: string;
    heroBackgroundColor: string;
    buttonTextColor: string;
    cardBackgroundColor: string;
    heroImage?: ExternalBlob;
    buttonColor: string;
    bannerBackgroundColor: string;
    overlayOpacity: bigint;
    headingShadowColor: string;
    cardTextColor: string;
}): Promise<{
    subtitleColor: string;
    headingColor: string;
    supportingTextColor: string;
    backgroundColorOverlay: string;
    heroBackgroundColor: string;
    buttonTextColor: string;
    cardBackgroundColor: string;
    heroImage: [] | [_ExternalBlob];
    buttonColor: string;
    bannerBackgroundColor: string;
    overlayOpacity: bigint;
    headingShadowColor: string;
    cardTextColor: string;
}> {
    return {
        subtitleColor: value.subtitleColor,
        headingColor: value.headingColor,
        supportingTextColor: value.supportingTextColor,
        backgroundColorOverlay: value.backgroundColorOverlay,
        heroBackgroundColor: value.heroBackgroundColor,
        buttonTextColor: value.buttonTextColor,
        cardBackgroundColor: value.cardBackgroundColor,
        heroImage: value.heroImage ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.heroImage)) : candid_none(),
        buttonColor: value.buttonColor,
        bannerBackgroundColor: value.bannerBackgroundColor,
        overlayOpacity: value.overlayOpacity,
        headingShadowColor: value.headingShadowColor,
        cardTextColor: value.cardTextColor
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
